attributes:
  metadata:
    restrictions:
      - "settings:common.libvirt_type.value == 'kvm'"
      - "settings:storage.volumes_ceph.value == true"
      - "settings:storage.images_ceph.value == true"
      - "settings:storage.ephemeral_ceph.value == true"
      - "settings:storage.objects_ceph.value == true"
      - "settings:additional_components.sahara.value == true"
      - "settings:additional_components.murano.value == true"
      - "settings:additional_components.mongo.value == true"
      - "settings:additional_components.ironic.value == true"
    group: 'compute'
  username:
    value: 'root'
    label: 'Username'
    description: ''
    weight: 10
    type: "text"
  password:
    value: ''
    label: 'Password'
    description: ''
    weight: 20
    type: "password"
    regex:
      source: '\S'
      error: "Password cannot be empty"
  install_xapi:
    value: true
    label: 'Install Nova Plugins'
    description: ''
    weight: 30
    type: "checkbox"
