attributes:
  username:
    value: 'root'
    label: 'Username'
    description: ''
    weight: 25
    type: "text"
  password:
    value: ''
    label: 'Password'
    description: ''
    weight: 25
    type: "password"
    regex:
      source: '\S'
      error: "Password cannot be empty"