- id: 'install-pv-tool'
  version: 2.0.0
  role: ['compute']
  required_for: ['compute-pre-test']
  requires: ['network_configuration_end']
  type: shell
  parameters:
    cmd: 'dpkg -i ./xe-guest-utilities_6.5.0-1393_amd64.deb'
    timeout: 60
- id: 'compute-pre-test'
  version: 2.0.0
  role: ['compute']
  requires: ['install-pv-tool']
  type: shell
  parameters:
    cmd: ./compute_pre_test.py
    timeout: 120
- id: 'compute-post-deployment'
  version: 2.0.0
  role: ['compute']
  required_for: ['post_deployment_end']
  requires: ['post_deployment_start']
  type: shell
  parameters:
    cmd: ./compute_post_deployment.py
    timeout: 300
- id: 'controller-post-deployment'
  version: 2.0.0
  role: ['primary-controller', 'controller']
  required_for: ['primary-controller-post-deployment']
  requires: ['post_deployment_start']
  type: shell
  parameters:
    cmd: ./controller_post_deployment.py
    timeout: 600
- id: 'primary-controller-post-deployment'
  version: 2.0.0
  role: ['primary-controller']
  required_for: ['post_deployment_end']
  requires: ['controller-post-deployment']
  type: shell
  parameters:
    cmd: source /root/openrc && ./primary_controller_post_deployment.py
    timeout: 600
